/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyFrame2;

import java.awt.Button;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ky
 */
public class FtimKiem extends javax.swing.JFrame {

    /**
     * Creates new form FtimKiem
     */
    private ArrayList<SinhVien> ds = new ArrayList<>(); // Danh sách sinh viên
    private DefaultTableModel Tmodel; // Model cho JTable
    public FtimKiem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        txttenlop = new java.awt.TextField();
        button1 = new java.awt.Button();
        label2 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        bang = new javax.swing.JTable();
        btnLenLop = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setText("Nhập tên lớp");

        txttenlop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttenlopKeyPressed(evt);
            }
        });

        button1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button1.setLabel("hiển thị tất cả");
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button1MousePressed(evt);
            }
        });

        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("Danh sách các sinh viên tìm được:");

        bang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sinh viên", "Họ tên", "Lớp", "Điểm trung bình", "Đậu/Rớt"
            }
        ));
        jScrollPane1.setViewportView(bang);

        btnLenLop.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnLenLop.setLabel("Ds lên lớp");
        btnLenLop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLenLopMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttenlop, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLenLop, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttenlop, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLenLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            BufferedReader read = new BufferedReader(new FileReader("ds.txt"));
            ds.clear();
            while (true) {
                String masv = read.readLine();
                if (masv == null) break;
                String ht = read.readLine();
                String tenlop = read.readLine();
                float dtb = Float.parseFloat(read.readLine());
                ds.add(new SinhVien(masv, ht, tenlop, dtb));
            }
            read.close();
            loadTableData();
        } catch (Exception tt) {
            JOptionPane.showMessageDialog(this, "Không mở được file!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowOpened

    private void txttenlopKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttenlopKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String tenLopNhap = txttenlop.getText().trim();
            if (tenLopNhap.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập tên lớp!", "Lỗi", JOptionPane.WARNING_MESSAGE);
                return;
            }
            DefaultTableModel Tmodel = (DefaultTableModel) bang.getModel();
            Tmodel.setRowCount(0);
            boolean found = false;
            for (SinhVien sv : ds) {
                if (sv.tenlop.equalsIgnoreCase(tenLopNhap)) {
                    Tmodel.addRow(new Object[]{sv.masv, sv.ht, sv.tenlop, sv.dtb});
                    found = true;
                }
            }
            if (!found) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy sinh viên lớp: " + tenLopNhap, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_txttenlopKeyPressed
public ArrayList<SinhVien> getDs() {
    return ds; // Trả về danh sách sinh viên
}

    private void button1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MousePressed
        DefaultTableModel Tmodel = (DefaultTableModel) bang.getModel();
        Tmodel.setRowCount(0);

        if (ds.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Danh sách sinh viên trống!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        for (SinhVien sv : ds) {
            String ketQua = (sv.dtb >= 5) ? "Đậu" : "Rớt"; // Xác định kết quả
            Tmodel.addRow(new Object[]{sv.masv, sv.ht, sv.tenlop, sv.dtb, ketQua});
        }
    }//GEN-LAST:event_button1MousePressed

    private void btnLenLopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLenLopMousePressed
        // TODO add your handling code here:
        DefaultTableModel Tmodel = (DefaultTableModel) bang.getModel();
    Tmodel.setRowCount(0);

    if (ds.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Danh sách sinh viên trống!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    for (SinhVien sv : ds) {
        if (sv.dtb >= 5) { // Chỉ hiển thị sinh viên có điểm >= 5
            Tmodel.addRow(new Object[]{sv.masv, sv.ht, sv.tenlop, sv.dtb, "Đậu"});
        }
    }
    }//GEN-LAST:event_btnLenLopMousePressed

    private void loadTableData() {
        DefaultTableModel Tmodel = (DefaultTableModel) bang.getModel();
        Tmodel.setRowCount(0);
        for (SinhVien sv : ds) {
            Tmodel.addRow(new Object[]{sv.masv, sv.ht, sv.tenlop, sv.dtb});
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FtimKiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FtimKiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FtimKiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FtimKiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FtimKiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bang;
    private java.awt.Button btnLenLop;
    private java.awt.Button button1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.TextField txttenlop;
    // End of variables declaration//GEN-END:variables
}
